### ISSUE TITLE
Is the latter .win32 a mistake?

### ISSUE THREAD

**Issue by sttk** [jonschlinkert/is-absolute#6]
(index.js:23)
```js
 return isWindows() ? isAbsolute.win32(fp) : isAbsolute.win32(fp);
```

**Comment by jonschlinkert** [comment]
yes! thanks for the heads up! I just did this a couple days ago, obviously during an air-head moment. 

thanks!

**Comment by sttk** [comment]
I'm about to use this module. Thanks.
